# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anubhav/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.srcs/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s01_mmu_2/kv260_ispMipiRx_vcu_DP_s01_mmu_2.xci
# IP: The module: 'kv260_ispMipiRx_vcu_DP_s01_mmu_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anubhav/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s01_mmu_2/kv260_ispMipiRx_vcu_DP_s01_mmu_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_ispMipiRx_vcu_DP_s01_mmu_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/anubhav/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.srcs/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s01_mmu_2/kv260_ispMipiRx_vcu_DP_s01_mmu_2.xci
# IP: The module: 'kv260_ispMipiRx_vcu_DP_s01_mmu_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anubhav/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s01_mmu_2/kv260_ispMipiRx_vcu_DP_s01_mmu_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kv260_ispMipiRx_vcu_DP_s01_mmu_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
