# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anubhav/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_fb21_vfb_0_0_axis_converter.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fb21_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_fb21_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: /home/anubhav/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_fb21_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fb21_vfb_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/anubhav/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/ip_0/bd_fb21_vfb_0_0_axis_converter.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_fb21_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_fb21_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: /home/anubhav/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_fb21_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_fb21_vfb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
