// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_MultiPixStream2Bytes (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_dout,
        img_num_data_valid,
        img_fifo_cap,
        img_empty_n,
        img_read,
        bytePlanes_plane01_din,
        bytePlanes_plane01_num_data_valid,
        bytePlanes_plane01_fifo_cap,
        bytePlanes_plane01_full_n,
        bytePlanes_plane01_write,
        bytePlanes_plane12_din,
        bytePlanes_plane12_num_data_valid,
        bytePlanes_plane12_fifo_cap,
        bytePlanes_plane12_full_n,
        bytePlanes_plane12_write,
        Height_dout,
        Height_num_data_valid,
        Height_fifo_cap,
        Height_empty_n,
        Height_read,
        WidthInBytes_dout,
        WidthInBytes_num_data_valid,
        WidthInBytes_fifo_cap,
        WidthInBytes_empty_n,
        WidthInBytes_read,
        VideoFormat_dout,
        VideoFormat_num_data_valid,
        VideoFormat_fifo_cap,
        VideoFormat_empty_n,
        VideoFormat_read,
        WidthInBytes_c_din,
        WidthInBytes_c_num_data_valid,
        WidthInBytes_c_fifo_cap,
        WidthInBytes_c_full_n,
        WidthInBytes_c_write,
        height_c_din,
        height_c_num_data_valid,
        height_c_fifo_cap,
        height_c_full_n,
        height_c_write,
        video_format_c_din,
        video_format_c_num_data_valid,
        video_format_c_fifo_cap,
        video_format_c_full_n,
        video_format_c_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [47:0] img_dout;
input  [1:0] img_num_data_valid;
input  [1:0] img_fifo_cap;
input   img_empty_n;
output   img_read;
output  [127:0] bytePlanes_plane01_din;
input  [9:0] bytePlanes_plane01_num_data_valid;
input  [9:0] bytePlanes_plane01_fifo_cap;
input   bytePlanes_plane01_full_n;
output   bytePlanes_plane01_write;
output  [127:0] bytePlanes_plane12_din;
input  [9:0] bytePlanes_plane12_num_data_valid;
input  [9:0] bytePlanes_plane12_fifo_cap;
input   bytePlanes_plane12_full_n;
output   bytePlanes_plane12_write;
input  [11:0] Height_dout;
input  [1:0] Height_num_data_valid;
input  [1:0] Height_fifo_cap;
input   Height_empty_n;
output   Height_read;
input  [14:0] WidthInBytes_dout;
input  [2:0] WidthInBytes_num_data_valid;
input  [2:0] WidthInBytes_fifo_cap;
input   WidthInBytes_empty_n;
output   WidthInBytes_read;
input  [5:0] VideoFormat_dout;
input  [2:0] VideoFormat_num_data_valid;
input  [2:0] VideoFormat_fifo_cap;
input   VideoFormat_empty_n;
output   VideoFormat_read;
output  [14:0] WidthInBytes_c_din;
input  [1:0] WidthInBytes_c_num_data_valid;
input  [1:0] WidthInBytes_c_fifo_cap;
input   WidthInBytes_c_full_n;
output   WidthInBytes_c_write;
output  [11:0] height_c_din;
input  [1:0] height_c_num_data_valid;
input  [1:0] height_c_fifo_cap;
input   height_c_full_n;
output   height_c_write;
output  [5:0] video_format_c_din;
input  [1:0] video_format_c_num_data_valid;
input  [1:0] video_format_c_fifo_cap;
input   video_format_c_full_n;
output   video_format_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_read;
reg bytePlanes_plane01_write;
reg bytePlanes_plane12_write;
reg Height_read;
reg WidthInBytes_read;
reg VideoFormat_read;
reg WidthInBytes_c_write;
reg height_c_write;
reg video_format_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Height_blk_n;
reg    WidthInBytes_blk_n;
reg    VideoFormat_blk_n;
reg    WidthInBytes_c_blk_n;
reg    height_c_blk_n;
reg    video_format_c_blk_n;
wire   [5:0] VideoFormat_read_read_fu_158_p2;
reg   [5:0] VideoFormat_read_reg_403;
reg   [11:0] Height_read_reg_407;
reg   [14:0] widthInPix_reg_412;
wire   [0:0] notlhs_fu_229_p2;
reg   [0:0] notlhs_reg_450;
wire   [11:0] trunc_ln571_1_fu_252_p4;
reg   [11:0] trunc_ln571_1_reg_455;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln576_fu_262_p2;
reg   [0:0] icmp_ln576_reg_460;
wire   [11:0] sub50_fu_289_p2;
reg   [11:0] sub50_reg_465;
wire   [0:0] cmp53_fu_295_p2;
reg   [0:0] cmp53_reg_470;
wire   [0:0] icmp_fu_311_p2;
reg   [0:0] icmp_reg_475;
wire   [0:0] cmp53_2_fu_317_p2;
reg   [0:0] cmp53_2_reg_480;
wire   [0:0] icmp6_fu_333_p2;
reg   [0:0] icmp6_reg_485;
wire   [0:0] cmp53_4_fu_339_p2;
reg   [0:0] cmp53_4_reg_490;
wire   [0:0] cmp53_5_fu_345_p2;
reg   [0:0] cmp53_5_reg_495;
wire   [0:0] cmp53_6_fu_351_p2;
reg   [0:0] cmp53_6_reg_500;
reg   [7:0] p_0_0_0_0_0_751_lcssa99_load_reg_508;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln583_fu_364_p2;
reg   [7:0] p_0_1_0_0_0_760_lcssa102_load_reg_513;
reg   [7:0] p_0_3_0_0_0_778_lcssa108_load_reg_518;
reg   [7:0] p_0_4_0_0_0_787_lcssa111_load_reg_523;
wire   [0:0] brmerge42_fu_393_p2;
reg   [0:0] brmerge42_reg_528;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_img_read;
wire   [127:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_write;
wire   [127:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_write;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out_ap_vld;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out_ap_vld;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out_ap_vld;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out_ap_vld;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [7:0] p_0_4_0_0_0_787_lcssa111_fu_154;
reg   [7:0] p_0_3_0_0_0_778_lcssa108_fu_150;
reg   [7:0] p_0_1_0_0_0_760_lcssa102_fu_146;
reg   [7:0] p_0_0_0_0_0_751_lcssa99_fu_142;
reg   [11:0] y_fu_138;
wire   [11:0] y_2_fu_369_p2;
reg    ap_block_state1;
wire   [15:0] zext_ln571_fu_243_p1;
wire   [15:0] add_ln571_fu_246_p2;
wire   [3:0] remainPix_fu_240_p1;
wire   [2:0] lshr_ln_fu_268_p4;
wire   [3:0] zext_ln578_fu_277_p1;
wire   [3:0] remainPix_1_fu_281_p3;
wire   [2:0] tmp_fu_301_p4;
wire   [1:0] tmp_1_fu_323_p4;
wire   [0:0] trunc_ln583_fu_360_p1;
wire   [0:0] tobool_not_fu_387_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg = 1'b0;
end

kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_img_read),
    .p_0_4_0_0_0_787_lcssa111(p_0_4_0_0_0_787_lcssa111_load_reg_523),
    .p_0_3_0_0_0_778_lcssa108(p_0_3_0_0_0_778_lcssa108_load_reg_518),
    .p_0_1_0_0_0_760_lcssa102(p_0_1_0_0_0_760_lcssa102_load_reg_513),
    .p_0_0_0_0_0_751_lcssa99(p_0_0_0_0_0_751_lcssa99_load_reg_508),
    .trunc_ln571_1(trunc_ln571_1_reg_455),
    .bytePlanes_plane12_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_din),
    .bytePlanes_plane12_num_data_valid(10'd0),
    .bytePlanes_plane12_fifo_cap(10'd0),
    .bytePlanes_plane12_full_n(bytePlanes_plane12_full_n),
    .bytePlanes_plane12_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_write),
    .bytePlanes_plane01_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_din),
    .bytePlanes_plane01_num_data_valid(10'd0),
    .bytePlanes_plane01_fifo_cap(10'd0),
    .bytePlanes_plane01_full_n(bytePlanes_plane01_full_n),
    .bytePlanes_plane01_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_write),
    .brmerge42(brmerge42_reg_528),
    .icmp_ln576(icmp_ln576_reg_460),
    .cmp53_6(cmp53_6_reg_500),
    .cmp53_5(cmp53_5_reg_495),
    .cmp53_4(cmp53_4_reg_490),
    .cmp53_3(icmp6_reg_485),
    .cmp53_2(cmp53_2_reg_480),
    .cmp53_1(icmp_reg_475),
    .sub50_cast38(sub50_reg_465),
    .cmp53(cmp53_reg_470),
    .p_0_4_0_0_0_786_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out),
    .p_0_4_0_0_0_786_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out_ap_vld),
    .p_0_3_0_0_0_777_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out),
    .p_0_3_0_0_0_777_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out_ap_vld),
    .p_0_1_0_0_0_759_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out),
    .p_0_1_0_0_0_759_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out_ap_vld),
    .p_0_0_0_0_0_750_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out),
    .p_0_0_0_0_0_750_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln583_fu_364_p2 == 1'd1) | (~(6'd18 == VideoFormat_read_reg_403) & ~(6'd19 == VideoFormat_read_reg_403))))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & ((6'd19 == VideoFormat_read_read_fu_158_p2) | (6'd18 == VideoFormat_read_read_fu_158_p2)))) begin
        y_fu_138 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln583_fu_364_p2 == 1'd0) & (6'd18 == VideoFormat_read_reg_403)) | ((6'd19 == VideoFormat_read_reg_403) & (icmp_ln583_fu_364_p2 == 1'd0))))) begin
        y_fu_138 <= y_2_fu_369_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        Height_read_reg_407 <= Height_dout;
        VideoFormat_read_reg_403 <= VideoFormat_dout;
        widthInPix_reg_412 <= WidthInBytes_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln583_fu_364_p2 == 1'd0) & (6'd18 == VideoFormat_read_reg_403)) | ((6'd19 == VideoFormat_read_reg_403) & (icmp_ln583_fu_364_p2 == 1'd0))))) begin
        brmerge42_reg_528 <= brmerge42_fu_393_p2;
        p_0_0_0_0_0_751_lcssa99_load_reg_508 <= p_0_0_0_0_0_751_lcssa99_fu_142;
        p_0_1_0_0_0_760_lcssa102_load_reg_513 <= p_0_1_0_0_0_760_lcssa102_fu_146;
        p_0_3_0_0_0_778_lcssa108_load_reg_518 <= p_0_3_0_0_0_778_lcssa108_fu_150;
        p_0_4_0_0_0_787_lcssa111_load_reg_523 <= p_0_4_0_0_0_787_lcssa111_fu_154;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp53_2_reg_480 <= cmp53_2_fu_317_p2;
        cmp53_4_reg_490 <= cmp53_4_fu_339_p2;
        cmp53_5_reg_495 <= cmp53_5_fu_345_p2;
        cmp53_6_reg_500 <= cmp53_6_fu_351_p2;
        cmp53_reg_470 <= cmp53_fu_295_p2;
        icmp6_reg_485 <= icmp6_fu_333_p2;
        icmp_ln576_reg_460 <= icmp_ln576_fu_262_p2;
        icmp_reg_475 <= icmp_fu_311_p2;
        sub50_reg_465 <= sub50_fu_289_p2;
        trunc_ln571_1_reg_455 <= {{add_ln571_fu_246_p2[15:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & ((6'd19 == VideoFormat_read_read_fu_158_p2) | (6'd18 == VideoFormat_read_read_fu_158_p2)))) begin
        notlhs_reg_450 <= notlhs_fu_229_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out_ap_vld == 1'b1))) begin
        p_0_0_0_0_0_751_lcssa99_fu_142 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out_ap_vld == 1'b1))) begin
        p_0_1_0_0_0_760_lcssa102_fu_146 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out_ap_vld == 1'b1))) begin
        p_0_3_0_0_0_778_lcssa108_fu_150 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out_ap_vld == 1'b1))) begin
        p_0_4_0_0_0_787_lcssa111_fu_154 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_blk_n = Height_empty_n;
    end else begin
        Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read = 1'b1;
    end else begin
        Height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_blk_n = VideoFormat_empty_n;
    end else begin
        VideoFormat_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_read = 1'b1;
    end else begin
        VideoFormat_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_blk_n = WidthInBytes_empty_n;
    end else begin
        WidthInBytes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_c_blk_n = WidthInBytes_c_full_n;
    end else begin
        WidthInBytes_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_c_write = 1'b1;
    end else begin
        WidthInBytes_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_read = 1'b1;
    end else begin
        WidthInBytes_read = 1'b0;
    end
end

always @ (*) begin
    if (((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln583_fu_364_p2 == 1'd1) | (~(6'd18 == VideoFormat_read_reg_403) & ~(6'd19 == VideoFormat_read_reg_403))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln583_fu_364_p2 == 1'd1) | (~(6'd18 == VideoFormat_read_reg_403) & ~(6'd19 == VideoFormat_read_reg_403))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bytePlanes_plane01_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_write;
    end else begin
        bytePlanes_plane01_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bytePlanes_plane12_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_write;
    end else begin
        bytePlanes_plane12_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_blk_n = height_c_full_n;
    end else begin
        height_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_write = 1'b1;
    end else begin
        height_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_img_read;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        video_format_c_blk_n = video_format_c_full_n;
    end else begin
        video_format_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        video_format_c_write = 1'b1;
    end else begin
        video_format_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & ~(6'd18 == VideoFormat_read_read_fu_158_p2) & ~(6'd19 == VideoFormat_read_read_fu_158_p2) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & ((6'd19 == VideoFormat_read_read_fu_158_p2) | (6'd18 == VideoFormat_read_read_fu_158_p2)))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & ((icmp_ln583_fu_364_p2 == 1'd1) | (~(6'd18 == VideoFormat_read_reg_403) & ~(6'd19 == VideoFormat_read_reg_403))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign VideoFormat_read_read_fu_158_p2 = VideoFormat_dout;

assign WidthInBytes_c_din = WidthInBytes_dout;

assign add_ln571_fu_246_p2 = (zext_ln571_fu_243_p1 + 16'd15);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign brmerge42_fu_393_p2 = (tobool_not_fu_387_p2 | notlhs_reg_450);

assign bytePlanes_plane01_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_din;

assign bytePlanes_plane12_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_din;

assign cmp53_2_fu_317_p2 = ((remainPix_1_fu_281_p3 > 4'd2) ? 1'b1 : 1'b0);

assign cmp53_4_fu_339_p2 = ((remainPix_1_fu_281_p3 > 4'd4) ? 1'b1 : 1'b0);

assign cmp53_5_fu_345_p2 = ((remainPix_1_fu_281_p3 > 4'd5) ? 1'b1 : 1'b0);

assign cmp53_6_fu_351_p2 = ((remainPix_1_fu_281_p3 > 4'd6) ? 1'b1 : 1'b0);

assign cmp53_fu_295_p2 = ((remainPix_1_fu_281_p3 != 4'd0) ? 1'b1 : 1'b0);

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg;

assign height_c_din = Height_dout;

assign icmp6_fu_333_p2 = ((tmp_1_fu_323_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_fu_311_p2 = ((tmp_fu_301_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln576_fu_262_p2 = ((remainPix_fu_240_p1 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln583_fu_364_p2 = ((y_fu_138 == Height_read_reg_407) ? 1'b1 : 1'b0);

assign lshr_ln_fu_268_p4 = {{widthInPix_reg_412[3:1]}};

assign notlhs_fu_229_p2 = ((VideoFormat_dout != 6'd19) ? 1'b1 : 1'b0);

assign remainPix_1_fu_281_p3 = ((icmp_ln576_fu_262_p2[0:0] == 1'b1) ? 4'd8 : zext_ln578_fu_277_p1);

assign remainPix_fu_240_p1 = widthInPix_reg_412[3:0];

assign sub50_fu_289_p2 = ($signed(trunc_ln571_1_fu_252_p4) + $signed(12'd4095));

assign tmp_1_fu_323_p4 = {{remainPix_1_fu_281_p3[3:2]}};

assign tmp_fu_301_p4 = {{remainPix_1_fu_281_p3[3:1]}};

assign tobool_not_fu_387_p2 = (trunc_ln583_fu_360_p1 ^ 1'd1);

assign trunc_ln571_1_fu_252_p4 = {{add_ln571_fu_246_p2[15:4]}};

assign trunc_ln583_fu_360_p1 = y_fu_138[0:0];

assign video_format_c_din = VideoFormat_dout;

assign y_2_fu_369_p2 = (y_fu_138 + 12'd1);

assign zext_ln571_fu_243_p1 = widthInPix_reg_412;

assign zext_ln578_fu_277_p1 = lshr_ln_fu_268_p4;

endmodule //kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_MultiPixStream2Bytes
