-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    img_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_empty_n : IN STD_LOGIC;
    img_read : OUT STD_LOGIC;
    p_0_4_0_0_0_787_lcssa111 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_3_0_0_0_778_lcssa108 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_0_760_lcssa102 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_0_751_lcssa99 : IN STD_LOGIC_VECTOR (7 downto 0);
    trunc_ln571_1 : IN STD_LOGIC_VECTOR (11 downto 0);
    bytePlanes_plane12_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    bytePlanes_plane12_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
    bytePlanes_plane12_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
    bytePlanes_plane12_full_n : IN STD_LOGIC;
    bytePlanes_plane12_write : OUT STD_LOGIC;
    bytePlanes_plane01_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    bytePlanes_plane01_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
    bytePlanes_plane01_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
    bytePlanes_plane01_full_n : IN STD_LOGIC;
    bytePlanes_plane01_write : OUT STD_LOGIC;
    brmerge42 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln576 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp53_6 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp53_5 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp53_4 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp53_3 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp53_2 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp53_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    sub50_cast38 : IN STD_LOGIC_VECTOR (11 downto 0);
    cmp53 : IN STD_LOGIC_VECTOR (0 downto 0);
    p_0_4_0_0_0_786_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_4_0_0_0_786_out_ap_vld : OUT STD_LOGIC;
    p_0_3_0_0_0_777_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_3_0_0_0_777_out_ap_vld : OUT STD_LOGIC;
    p_0_1_0_0_0_759_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_0_759_out_ap_vld : OUT STD_LOGIC;
    p_0_0_0_0_0_750_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_0_750_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal icmp_ln586_reg_992 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln590_1_reg_1016 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op69_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal or_ln590_6_reg_1071 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op130_read_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage7_iter0 : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal bytePlanes_plane12_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal bytePlanes_plane01_blk_n : STD_LOGIC;
    signal img_blk_n : STD_LOGIC;
    signal or_ln590_reg_1007 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal or_ln590_2_reg_1045 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal or_ln590_3_reg_1054 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal or_ln590_4_reg_1063 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6 : BOOLEAN;
    signal or_ln590_5_reg_1067 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage7 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal or_ln590_7_reg_1075 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_4_0_0_0_785_reg_236 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_3_0_0_0_776_reg_246 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0_758_reg_256 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0_749_reg_266 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_4_0_0_0_784_reg_276 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_3_0_0_0_775_reg_287 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0_757_reg_298 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0_748_reg_309 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_4_0_0_0_783_reg_320 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_3_0_0_0_774_reg_331 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0_756_reg_342 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0_747_reg_353 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_4_0_0_0_782_reg_364 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_3_0_0_0_773_reg_375 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0_755_reg_386 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0_746_reg_397 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_4_0_0_0_781_reg_408 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_3_0_0_0_772_reg_419 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0_754_reg_430 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0_745_reg_441 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_4_0_0_0_780_reg_452 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_3_0_0_0_771_reg_463 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0_753_reg_474 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0_744_reg_485 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_predicate_op54_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state10_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_predicate_op93_read_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_predicate_op108_read_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage5_iter0 : BOOLEAN;
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op141_read_state9 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_predicate_op81_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_predicate_op119_read_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage6_iter0 : BOOLEAN;
    signal ap_block_pp0_stage6_11001 : BOOLEAN;
    signal icmp_ln586_fu_695_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln586_reg_992_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp51_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp51_reg_996 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln590_fu_717_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln145_fu_728_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln590_1_fu_732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln145_4_fu_748_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln590_2_fu_752_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln145_5_fu_756_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln590_3_fu_760_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln145_8_fu_764_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln590_4_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln590_5_fu_772_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln590_6_fu_776_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln590_7_fu_780_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln145_11_fu_784_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln145_14_fu_788_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln145_17_fu_792_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage7_11001 : BOOLEAN;
    signal trunc_ln145_20_fu_796_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_p_0_4_0_0_0_785_reg_236 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_3_0_0_0_776_reg_246 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_1_0_0_0_758_reg_256 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_0_0_0_0_749_reg_266 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_4_0_0_0_784_reg_276 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_3_0_0_0_775_reg_287 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_1_0_0_0_757_reg_298 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_0_0_0_0_748_reg_309 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_4_0_0_0_783_reg_320 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_3_0_0_0_774_reg_331 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_1_0_0_0_756_reg_342 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_0_0_0_0_747_reg_353 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_4_0_0_0_782_reg_364 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_3_0_0_0_773_reg_375 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_1_0_0_0_755_reg_386 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_0_0_0_0_746_reg_397 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_4_0_0_0_781_reg_408 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_3_0_0_0_772_reg_419 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_1_0_0_0_754_reg_430 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_0_0_0_0_745_reg_441 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_4_0_0_0_780_reg_452 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_4_0_0_0_780_reg_452 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_3_0_0_0_771_reg_463 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_3_0_0_0_771_reg_463 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_1_0_0_0_753_reg_474 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_1_0_0_0_753_reg_474 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_0_0_0_0_744_reg_485 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_0_0_0_0_744_reg_485 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_4_0_0_0_779_reg_496 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_4_0_0_0_779_reg_496 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_3_0_0_0_770_reg_506 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_3_0_0_0_770_reg_506 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_1_0_0_0_752_reg_516 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_1_0_0_0_752_reg_516 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_0_0_0_0_743_reg_526 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_0_0_0_0_743_reg_526 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_0_4_0_0_0_787_phi_fu_539_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_4_0_0_0_787_reg_536 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_4_0_0_0_787_reg_536 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_0_3_0_0_0_778_phi_fu_549_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_3_0_0_0_778_reg_546 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_3_0_0_0_778_reg_546 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_0_1_0_0_0_760_phi_fu_559_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_1_0_0_0_760_reg_556 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_1_0_0_0_760_reg_556 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_p_0_0_0_0_0_751_phi_fu_569_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_p_0_0_0_0_0_751_reg_566 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_p_0_0_0_0_0_751_reg_566 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_fu_106 : STD_LOGIC_VECTOR (11 downto 0);
    signal x_2_fu_701_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_0_0_0_0_0_750_fu_110 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0_759_fu_114 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_3_0_0_0_777_fu_118 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_4_0_0_0_786_fu_122 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal zext_ln586_fu_707_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub50_cast38_cast_fu_663_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_865 : BOOLEAN;
    signal ap_condition_868 : BOOLEAN;
    signal ap_condition_871 : BOOLEAN;
    signal ap_condition_874 : BOOLEAN;
    signal ap_condition_877 : BOOLEAN;
    signal ap_condition_880 : BOOLEAN;
    signal ap_condition_884 : BOOLEAN;
    signal ap_condition_888 : BOOLEAN;
    signal ap_condition_891 : BOOLEAN;
    signal ap_condition_894 : BOOLEAN;
    signal ap_condition_476 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_745_reg_441_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_868)) then 
                    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_745_reg_441 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_746_reg_397;
                elsif ((ap_const_boolean_1 = ap_condition_865)) then 
                    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_745_reg_441 <= trunc_ln145_11_fu_784_p1;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_746_reg_397_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_874)) then 
                    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_746_reg_397 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_747_reg_353;
                elsif ((ap_const_boolean_1 = ap_condition_871)) then 
                    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_746_reg_397 <= trunc_ln145_8_fu_764_p1;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_747_reg_353_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_880)) then 
                    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_747_reg_353 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_748_reg_309;
                elsif ((ap_const_boolean_1 = ap_condition_877)) then 
                    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_747_reg_353 <= trunc_ln145_5_fu_756_p1;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_748_reg_309_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_888)) then 
                    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_748_reg_309 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_749_reg_266;
                elsif ((ap_const_boolean_1 = ap_condition_884)) then 
                    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_748_reg_309 <= trunc_ln145_4_fu_748_p1;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_749_reg_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_894)) then 
                    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_749_reg_266 <= p_0_0_0_0_0_750_fu_110;
                elsif ((ap_const_boolean_1 = ap_condition_891)) then 
                    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_749_reg_266 <= trunc_ln145_fu_728_p1;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_754_reg_430_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_868)) then 
                    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_754_reg_430 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_755_reg_386;
                elsif ((ap_const_boolean_1 = ap_condition_865)) then 
                    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_754_reg_430 <= img_dout(15 downto 8);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_755_reg_386_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_874)) then 
                    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_755_reg_386 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_756_reg_342;
                elsif ((ap_const_boolean_1 = ap_condition_871)) then 
                    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_755_reg_386 <= img_dout(15 downto 8);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_756_reg_342_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_880)) then 
                    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_756_reg_342 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_757_reg_298;
                elsif ((ap_const_boolean_1 = ap_condition_877)) then 
                    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_756_reg_342 <= img_dout(15 downto 8);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_757_reg_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_888)) then 
                    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_757_reg_298 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_758_reg_256;
                elsif ((ap_const_boolean_1 = ap_condition_884)) then 
                    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_757_reg_298 <= img_dout(15 downto 8);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_758_reg_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_894)) then 
                    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_758_reg_256 <= p_0_1_0_0_0_759_fu_114;
                elsif ((ap_const_boolean_1 = ap_condition_891)) then 
                    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_758_reg_256 <= img_dout(15 downto 8);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_772_reg_419_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_868)) then 
                    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_772_reg_419 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_773_reg_375;
                elsif ((ap_const_boolean_1 = ap_condition_865)) then 
                    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_772_reg_419 <= img_dout(31 downto 24);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_773_reg_375_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_874)) then 
                    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_773_reg_375 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_774_reg_331;
                elsif ((ap_const_boolean_1 = ap_condition_871)) then 
                    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_773_reg_375 <= img_dout(31 downto 24);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_774_reg_331_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_880)) then 
                    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_774_reg_331 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_775_reg_287;
                elsif ((ap_const_boolean_1 = ap_condition_877)) then 
                    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_774_reg_331 <= img_dout(31 downto 24);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_775_reg_287_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_888)) then 
                    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_775_reg_287 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_776_reg_246;
                elsif ((ap_const_boolean_1 = ap_condition_884)) then 
                    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_775_reg_287 <= img_dout(31 downto 24);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_776_reg_246_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_894)) then 
                    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_776_reg_246 <= p_0_3_0_0_0_777_fu_118;
                elsif ((ap_const_boolean_1 = ap_condition_891)) then 
                    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_776_reg_246 <= img_dout(31 downto 24);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_781_reg_408_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_868)) then 
                    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_781_reg_408 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_782_reg_364;
                elsif ((ap_const_boolean_1 = ap_condition_865)) then 
                    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_781_reg_408 <= img_dout(39 downto 32);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_782_reg_364_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_874)) then 
                    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_782_reg_364 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_783_reg_320;
                elsif ((ap_const_boolean_1 = ap_condition_871)) then 
                    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_782_reg_364 <= img_dout(39 downto 32);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_783_reg_320_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_880)) then 
                    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_783_reg_320 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_784_reg_276;
                elsif ((ap_const_boolean_1 = ap_condition_877)) then 
                    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_783_reg_320 <= img_dout(39 downto 32);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_784_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_888)) then 
                    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_784_reg_276 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_785_reg_236;
                elsif ((ap_const_boolean_1 = ap_condition_884)) then 
                    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_784_reg_276 <= img_dout(39 downto 32);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_785_reg_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_894)) then 
                    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_785_reg_236 <= p_0_4_0_0_0_786_fu_122;
                elsif ((ap_const_boolean_1 = ap_condition_891)) then 
                    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_785_reg_236 <= img_dout(39 downto 32);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_0_0_0_0_743_reg_526_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln590_6_reg_1071 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_p_0_0_0_0_0_743_reg_526 <= ap_phi_reg_pp0_iter1_p_0_0_0_0_0_744_reg_485;
            elsif (((or_ln590_6_reg_1071 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_0_0_0_0_743_reg_526 <= trunc_ln145_17_fu_792_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_0_0_0_0_743_reg_526 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_743_reg_526;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_0_0_0_0_744_reg_485_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_476)) then
                if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (or_ln590_5_reg_1067 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_p_0_0_0_0_0_744_reg_485 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_745_reg_441;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_0_0_0_0_0_744_reg_485 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_744_reg_485;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_0_0_0_0_751_reg_566_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln590_7_reg_1075 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_p_0_0_0_0_0_751_reg_566 <= trunc_ln145_20_fu_796_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_0_0_0_0_751_reg_566 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_751_reg_566;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_1_0_0_0_752_reg_516_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln590_6_reg_1071 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_p_0_1_0_0_0_752_reg_516 <= ap_phi_reg_pp0_iter1_p_0_1_0_0_0_753_reg_474;
            elsif (((or_ln590_6_reg_1071 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_1_0_0_0_752_reg_516 <= img_dout(15 downto 8);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_1_0_0_0_752_reg_516 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_752_reg_516;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_1_0_0_0_753_reg_474_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_476)) then
                if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (or_ln590_5_reg_1067 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_p_0_1_0_0_0_753_reg_474 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_754_reg_430;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_0_1_0_0_0_753_reg_474 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_753_reg_474;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_1_0_0_0_760_reg_556_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln590_7_reg_1075 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_p_0_1_0_0_0_760_reg_556 <= img_dout(15 downto 8);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_1_0_0_0_760_reg_556 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_760_reg_556;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_3_0_0_0_770_reg_506_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln590_6_reg_1071 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_p_0_3_0_0_0_770_reg_506 <= ap_phi_reg_pp0_iter1_p_0_3_0_0_0_771_reg_463;
            elsif (((or_ln590_6_reg_1071 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_3_0_0_0_770_reg_506 <= img_dout(31 downto 24);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_3_0_0_0_770_reg_506 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_770_reg_506;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_3_0_0_0_771_reg_463_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_476)) then
                if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (or_ln590_5_reg_1067 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_p_0_3_0_0_0_771_reg_463 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_772_reg_419;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_0_3_0_0_0_771_reg_463 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_771_reg_463;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_3_0_0_0_778_reg_546_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln590_7_reg_1075 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_p_0_3_0_0_0_778_reg_546 <= img_dout(31 downto 24);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_3_0_0_0_778_reg_546 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_778_reg_546;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_4_0_0_0_779_reg_496_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_ln590_6_reg_1071 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_p_0_4_0_0_0_779_reg_496 <= ap_phi_reg_pp0_iter1_p_0_4_0_0_0_780_reg_452;
            elsif (((or_ln590_6_reg_1071 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_4_0_0_0_779_reg_496 <= img_dout(39 downto 32);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_4_0_0_0_779_reg_496 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_779_reg_496;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_4_0_0_0_780_reg_452_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_476)) then
                if (((icmp_ln586_reg_992 = ap_const_lv1_0) and (or_ln590_5_reg_1067 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_p_0_4_0_0_0_780_reg_452 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_781_reg_408;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_p_0_4_0_0_0_780_reg_452 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_780_reg_452;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_p_0_4_0_0_0_787_reg_536_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln590_7_reg_1075 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_p_0_4_0_0_0_787_reg_536 <= img_dout(39 downto 32);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_p_0_4_0_0_0_787_reg_536 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_787_reg_536;
            end if; 
        end if;
    end process;

    p_0_0_0_0_0_750_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0_0_0_0_0_750_fu_110 <= p_0_0_0_0_0_751_lcssa99;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                p_0_0_0_0_0_750_fu_110 <= ap_phi_mux_p_0_0_0_0_0_751_phi_fu_569_p4;
            end if; 
        end if;
    end process;

    p_0_1_0_0_0_759_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0_1_0_0_0_759_fu_114 <= p_0_1_0_0_0_760_lcssa102;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                p_0_1_0_0_0_759_fu_114 <= ap_phi_mux_p_0_1_0_0_0_760_phi_fu_559_p4;
            end if; 
        end if;
    end process;

    p_0_3_0_0_0_777_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0_3_0_0_0_777_fu_118 <= p_0_3_0_0_0_778_lcssa108;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                p_0_3_0_0_0_777_fu_118 <= ap_phi_mux_p_0_3_0_0_0_778_phi_fu_549_p4;
            end if; 
        end if;
    end process;

    p_0_4_0_0_0_786_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_0_4_0_0_0_786_fu_122 <= p_0_4_0_0_0_787_lcssa111;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                p_0_4_0_0_0_786_fu_122 <= ap_phi_mux_p_0_4_0_0_0_787_phi_fu_539_p4;
            end if; 
        end if;
    end process;

    x_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln586_fu_695_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_106 <= x_2_fu_701_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_106 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (or_ln590_5_reg_1067 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                ap_phi_reg_pp0_iter0_p_0_0_0_0_0_744_reg_485 <= trunc_ln145_14_fu_788_p1;
                ap_phi_reg_pp0_iter0_p_0_1_0_0_0_753_reg_474 <= img_dout(15 downto 8);
                ap_phi_reg_pp0_iter0_p_0_3_0_0_0_771_reg_463 <= img_dout(31 downto 24);
                ap_phi_reg_pp0_iter0_p_0_4_0_0_0_780_reg_452 <= img_dout(39 downto 32);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_fu_695_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                cmp51_reg_996 <= cmp51_fu_711_p2;
                or_ln590_reg_1007 <= or_ln590_fu_717_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln586_reg_992 <= icmp_ln586_fu_695_p2;
                icmp_ln586_reg_992_pp0_iter1_reg <= icmp_ln586_reg_992;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                or_ln590_1_reg_1016 <= or_ln590_1_fu_732_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                or_ln590_2_reg_1045 <= or_ln590_2_fu_752_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                or_ln590_3_reg_1054 <= or_ln590_3_fu_760_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                or_ln590_4_reg_1063 <= or_ln590_4_fu_768_p2;
                or_ln590_5_reg_1067 <= or_ln590_5_fu_772_p2;
                or_ln590_6_reg_1071 <= or_ln590_6_fu_776_p2;
                or_ln590_7_reg_1075 <= or_ln590_7_fu_780_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_0_0_0_0_0_744_reg_485 <= ap_phi_reg_pp0_iter1_p_0_0_0_0_0_744_reg_485;
                p_0_1_0_0_0_753_reg_474 <= ap_phi_reg_pp0_iter1_p_0_1_0_0_0_753_reg_474;
                p_0_3_0_0_0_771_reg_463 <= ap_phi_reg_pp0_iter1_p_0_3_0_0_0_771_reg_463;
                p_0_4_0_0_0_780_reg_452 <= ap_phi_reg_pp0_iter1_p_0_4_0_0_0_780_reg_452;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                p_0_0_0_0_0_745_reg_441 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_745_reg_441;
                p_0_1_0_0_0_754_reg_430 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_754_reg_430;
                p_0_3_0_0_0_772_reg_419 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_772_reg_419;
                p_0_4_0_0_0_781_reg_408 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_781_reg_408;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                p_0_0_0_0_0_746_reg_397 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_746_reg_397;
                p_0_1_0_0_0_755_reg_386 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_755_reg_386;
                p_0_3_0_0_0_773_reg_375 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_773_reg_375;
                p_0_4_0_0_0_782_reg_364 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_782_reg_364;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                p_0_0_0_0_0_747_reg_353 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_747_reg_353;
                p_0_1_0_0_0_756_reg_342 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_756_reg_342;
                p_0_3_0_0_0_774_reg_331 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_774_reg_331;
                p_0_4_0_0_0_783_reg_320 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_783_reg_320;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                p_0_0_0_0_0_748_reg_309 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_748_reg_309;
                p_0_1_0_0_0_757_reg_298 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_757_reg_298;
                p_0_3_0_0_0_775_reg_287 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_775_reg_287;
                p_0_4_0_0_0_784_reg_276 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_784_reg_276;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                p_0_0_0_0_0_749_reg_266 <= ap_phi_reg_pp0_iter0_p_0_0_0_0_0_749_reg_266;
                p_0_1_0_0_0_758_reg_256 <= ap_phi_reg_pp0_iter0_p_0_1_0_0_0_758_reg_256;
                p_0_3_0_0_0_776_reg_246 <= ap_phi_reg_pp0_iter0_p_0_3_0_0_0_776_reg_246;
                p_0_4_0_0_0_785_reg_236 <= ap_phi_reg_pp0_iter0_p_0_4_0_0_0_785_reg_236;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_condition_exit_pp0_iter0_stage2, ap_block_pp0_stage7_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, img_empty_n, ap_predicate_op141_read_state9)
    begin
                ap_block_pp0_stage0_11001 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op141_read_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, img_empty_n, ap_predicate_op141_read_state9)
    begin
                ap_block_pp0_stage0_subdone <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op141_read_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, img_empty_n, bytePlanes_plane12_full_n, bytePlanes_plane01_full_n, brmerge42, ap_predicate_op54_read_state2)
    begin
                ap_block_pp0_stage1_01001 <= (((img_empty_n = ap_const_logic_0) and (ap_predicate_op54_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((bytePlanes_plane01_full_n = ap_const_logic_0) or ((bytePlanes_plane12_full_n = ap_const_logic_0) and (brmerge42 = ap_const_lv1_1)))));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, img_empty_n, bytePlanes_plane12_full_n, bytePlanes_plane01_full_n, brmerge42, ap_predicate_op54_read_state2)
    begin
                ap_block_pp0_stage1_11001 <= (((img_empty_n = ap_const_logic_0) and (ap_predicate_op54_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((bytePlanes_plane01_full_n = ap_const_logic_0) or ((bytePlanes_plane12_full_n = ap_const_logic_0) and (brmerge42 = ap_const_lv1_1)))));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, img_empty_n, bytePlanes_plane12_full_n, bytePlanes_plane01_full_n, brmerge42, ap_predicate_op54_read_state2)
    begin
                ap_block_pp0_stage1_subdone <= (((img_empty_n = ap_const_logic_0) and (ap_predicate_op54_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((bytePlanes_plane01_full_n = ap_const_logic_0) or ((bytePlanes_plane12_full_n = ap_const_logic_0) and (brmerge42 = ap_const_lv1_1)))));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op69_read_state3)
    begin
                ap_block_pp0_stage2_11001 <= ((ap_predicate_op69_read_state3 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op69_read_state3)
    begin
                ap_block_pp0_stage2_subdone <= ((ap_predicate_op69_read_state3 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op81_read_state4)
    begin
                ap_block_pp0_stage3_11001 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op81_read_state4)
    begin
                ap_block_pp0_stage3_subdone <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op93_read_state5)
    begin
                ap_block_pp0_stage4_11001 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op93_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op93_read_state5)
    begin
                ap_block_pp0_stage4_subdone <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op93_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage5_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op108_read_state6)
    begin
                ap_block_pp0_stage5_11001 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op108_read_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage5_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op108_read_state6)
    begin
                ap_block_pp0_stage5_subdone <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op108_read_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage6_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op119_read_state7)
    begin
                ap_block_pp0_stage6_11001 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op119_read_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage6_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op119_read_state7)
    begin
                ap_block_pp0_stage6_subdone <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op119_read_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage7_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op130_read_state8)
    begin
                ap_block_pp0_stage7_11001 <= ((ap_predicate_op130_read_state8 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage7_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op130_read_state8)
    begin
                ap_block_pp0_stage7_subdone <= ((ap_predicate_op130_read_state8 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_state10_pp0_stage1_iter1_assign_proc : process(bytePlanes_plane12_full_n, bytePlanes_plane01_full_n, brmerge42)
    begin
                ap_block_state10_pp0_stage1_iter1 <= ((bytePlanes_plane01_full_n = ap_const_logic_0) or ((bytePlanes_plane12_full_n = ap_const_logic_0) and (brmerge42 = ap_const_lv1_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage1_iter0_assign_proc : process(img_empty_n, ap_predicate_op54_read_state2)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op54_read_state2 = ap_const_boolean_1));
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(img_empty_n, ap_predicate_op69_read_state3)
    begin
                ap_block_state3_pp0_stage2_iter0 <= ((ap_predicate_op69_read_state3 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage3_iter0_assign_proc : process(img_empty_n, ap_predicate_op81_read_state4)
    begin
                ap_block_state4_pp0_stage3_iter0 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op81_read_state4 = ap_const_boolean_1));
    end process;


    ap_block_state5_pp0_stage4_iter0_assign_proc : process(img_empty_n, ap_predicate_op93_read_state5)
    begin
                ap_block_state5_pp0_stage4_iter0 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op93_read_state5 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp0_stage5_iter0_assign_proc : process(img_empty_n, ap_predicate_op108_read_state6)
    begin
                ap_block_state6_pp0_stage5_iter0 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op108_read_state6 = ap_const_boolean_1));
    end process;


    ap_block_state7_pp0_stage6_iter0_assign_proc : process(img_empty_n, ap_predicate_op119_read_state7)
    begin
                ap_block_state7_pp0_stage6_iter0 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op119_read_state7 = ap_const_boolean_1));
    end process;


    ap_block_state8_pp0_stage7_iter0_assign_proc : process(img_empty_n, ap_predicate_op130_read_state8)
    begin
                ap_block_state8_pp0_stage7_iter0 <= ((ap_predicate_op130_read_state8 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0));
    end process;


    ap_block_state9_pp0_stage0_iter1_assign_proc : process(img_empty_n, ap_predicate_op141_read_state9)
    begin
                ap_block_state9_pp0_stage0_iter1 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op141_read_state9 = ap_const_boolean_1));
    end process;


    ap_condition_476_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_11001)
    begin
                ap_condition_476 <= ((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7));
    end process;


    ap_condition_865_assign_proc : process(ap_CS_fsm_pp0_stage5, or_ln590_4_reg_1063, ap_block_pp0_stage5_11001)
    begin
                ap_condition_865 <= ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (or_ln590_4_reg_1063 = ap_const_lv1_1));
    end process;


    ap_condition_868_assign_proc : process(or_ln590_4_reg_1063, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001)
    begin
                ap_condition_868 <= ((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6) and (or_ln590_4_reg_1063 = ap_const_lv1_0));
    end process;


    ap_condition_871_assign_proc : process(ap_CS_fsm_pp0_stage4, or_ln590_3_reg_1054, ap_block_pp0_stage4_11001)
    begin
                ap_condition_871 <= ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (or_ln590_3_reg_1054 = ap_const_lv1_1));
    end process;


    ap_condition_874_assign_proc : process(or_ln590_3_reg_1054, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001)
    begin
                ap_condition_874 <= ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (or_ln590_3_reg_1054 = ap_const_lv1_0));
    end process;


    ap_condition_877_assign_proc : process(ap_CS_fsm_pp0_stage3, or_ln590_2_reg_1045, ap_block_pp0_stage3_11001)
    begin
                ap_condition_877 <= ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (or_ln590_2_reg_1045 = ap_const_lv1_1));
    end process;


    ap_condition_880_assign_proc : process(or_ln590_2_reg_1045, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001)
    begin
                ap_condition_880 <= ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (or_ln590_2_reg_1045 = ap_const_lv1_0));
    end process;


    ap_condition_884_assign_proc : process(ap_CS_fsm_pp0_stage2, or_ln590_1_reg_1016, ap_block_pp0_stage2_11001)
    begin
                ap_condition_884 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (or_ln590_1_reg_1016 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2));
    end process;


    ap_condition_888_assign_proc : process(or_ln590_1_reg_1016, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
                ap_condition_888 <= ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (or_ln590_1_reg_1016 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3));
    end process;


    ap_condition_891_assign_proc : process(ap_CS_fsm_pp0_stage1, or_ln590_reg_1007, ap_block_pp0_stage1_11001)
    begin
                ap_condition_891 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln590_reg_1007 = ap_const_lv1_1));
    end process;


    ap_condition_894_assign_proc : process(ap_CS_fsm_pp0_stage2, or_ln590_reg_1007, ap_block_pp0_stage2_11001)
    begin
                ap_condition_894 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln590_reg_1007 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, icmp_ln586_reg_992, ap_block_pp0_stage2_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (icmp_ln586_reg_992 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;

    ap_phi_mux_p_0_0_0_0_0_751_phi_fu_569_p4_assign_proc : process(or_ln590_7_reg_1075, icmp_ln586_reg_992_pp0_iter1_reg, ap_phi_reg_pp0_iter1_p_0_0_0_0_0_743_reg_526, ap_phi_reg_pp0_iter1_p_0_0_0_0_0_751_reg_566)
    begin
        if (((icmp_ln586_reg_992_pp0_iter1_reg = ap_const_lv1_0) and (or_ln590_7_reg_1075 = ap_const_lv1_0))) then 
            ap_phi_mux_p_0_0_0_0_0_751_phi_fu_569_p4 <= ap_phi_reg_pp0_iter1_p_0_0_0_0_0_743_reg_526;
        else 
            ap_phi_mux_p_0_0_0_0_0_751_phi_fu_569_p4 <= ap_phi_reg_pp0_iter1_p_0_0_0_0_0_751_reg_566;
        end if; 
    end process;


    ap_phi_mux_p_0_1_0_0_0_760_phi_fu_559_p4_assign_proc : process(or_ln590_7_reg_1075, icmp_ln586_reg_992_pp0_iter1_reg, ap_phi_reg_pp0_iter1_p_0_1_0_0_0_752_reg_516, ap_phi_reg_pp0_iter1_p_0_1_0_0_0_760_reg_556)
    begin
        if (((icmp_ln586_reg_992_pp0_iter1_reg = ap_const_lv1_0) and (or_ln590_7_reg_1075 = ap_const_lv1_0))) then 
            ap_phi_mux_p_0_1_0_0_0_760_phi_fu_559_p4 <= ap_phi_reg_pp0_iter1_p_0_1_0_0_0_752_reg_516;
        else 
            ap_phi_mux_p_0_1_0_0_0_760_phi_fu_559_p4 <= ap_phi_reg_pp0_iter1_p_0_1_0_0_0_760_reg_556;
        end if; 
    end process;


    ap_phi_mux_p_0_3_0_0_0_778_phi_fu_549_p4_assign_proc : process(or_ln590_7_reg_1075, icmp_ln586_reg_992_pp0_iter1_reg, ap_phi_reg_pp0_iter1_p_0_3_0_0_0_770_reg_506, ap_phi_reg_pp0_iter1_p_0_3_0_0_0_778_reg_546)
    begin
        if (((icmp_ln586_reg_992_pp0_iter1_reg = ap_const_lv1_0) and (or_ln590_7_reg_1075 = ap_const_lv1_0))) then 
            ap_phi_mux_p_0_3_0_0_0_778_phi_fu_549_p4 <= ap_phi_reg_pp0_iter1_p_0_3_0_0_0_770_reg_506;
        else 
            ap_phi_mux_p_0_3_0_0_0_778_phi_fu_549_p4 <= ap_phi_reg_pp0_iter1_p_0_3_0_0_0_778_reg_546;
        end if; 
    end process;


    ap_phi_mux_p_0_4_0_0_0_787_phi_fu_539_p4_assign_proc : process(or_ln590_7_reg_1075, icmp_ln586_reg_992_pp0_iter1_reg, ap_phi_reg_pp0_iter1_p_0_4_0_0_0_779_reg_496, ap_phi_reg_pp0_iter1_p_0_4_0_0_0_787_reg_536)
    begin
        if (((icmp_ln586_reg_992_pp0_iter1_reg = ap_const_lv1_0) and (or_ln590_7_reg_1075 = ap_const_lv1_0))) then 
            ap_phi_mux_p_0_4_0_0_0_787_phi_fu_539_p4 <= ap_phi_reg_pp0_iter1_p_0_4_0_0_0_779_reg_496;
        else 
            ap_phi_mux_p_0_4_0_0_0_787_phi_fu_539_p4 <= ap_phi_reg_pp0_iter1_p_0_4_0_0_0_787_reg_536;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_743_reg_526 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_0_0_0_0_0_751_reg_566 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_752_reg_516 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_0_1_0_0_0_760_reg_556 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_770_reg_506 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_0_3_0_0_0_778_reg_546 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_779_reg_496 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_p_0_4_0_0_0_787_reg_536 <= "XXXXXXXX";

    ap_predicate_op108_read_state6_assign_proc : process(icmp_ln586_reg_992, or_ln590_4_reg_1063)
    begin
                ap_predicate_op108_read_state6 <= ((icmp_ln586_reg_992 = ap_const_lv1_0) and (or_ln590_4_reg_1063 = ap_const_lv1_1));
    end process;


    ap_predicate_op119_read_state7_assign_proc : process(icmp_ln586_reg_992, or_ln590_5_reg_1067)
    begin
                ap_predicate_op119_read_state7 <= ((icmp_ln586_reg_992 = ap_const_lv1_0) and (or_ln590_5_reg_1067 = ap_const_lv1_1));
    end process;


    ap_predicate_op130_read_state8_assign_proc : process(icmp_ln586_reg_992, or_ln590_6_reg_1071)
    begin
                ap_predicate_op130_read_state8 <= ((or_ln590_6_reg_1071 = ap_const_lv1_1) and (icmp_ln586_reg_992 = ap_const_lv1_0));
    end process;


    ap_predicate_op141_read_state9_assign_proc : process(icmp_ln586_reg_992, or_ln590_7_reg_1075)
    begin
                ap_predicate_op141_read_state9 <= ((icmp_ln586_reg_992 = ap_const_lv1_0) and (or_ln590_7_reg_1075 = ap_const_lv1_1));
    end process;


    ap_predicate_op54_read_state2_assign_proc : process(icmp_ln586_reg_992, or_ln590_reg_1007)
    begin
                ap_predicate_op54_read_state2 <= ((icmp_ln586_reg_992 = ap_const_lv1_0) and (or_ln590_reg_1007 = ap_const_lv1_1));
    end process;


    ap_predicate_op69_read_state3_assign_proc : process(icmp_ln586_reg_992, or_ln590_1_reg_1016)
    begin
                ap_predicate_op69_read_state3 <= ((or_ln590_1_reg_1016 = ap_const_lv1_1) and (icmp_ln586_reg_992 = ap_const_lv1_0));
    end process;


    ap_predicate_op81_read_state4_assign_proc : process(icmp_ln586_reg_992, or_ln590_2_reg_1045)
    begin
                ap_predicate_op81_read_state4 <= ((icmp_ln586_reg_992 = ap_const_lv1_0) and (or_ln590_2_reg_1045 = ap_const_lv1_1));
    end process;


    ap_predicate_op93_read_state5_assign_proc : process(icmp_ln586_reg_992, or_ln590_3_reg_1054)
    begin
                ap_predicate_op93_read_state5 <= ((icmp_ln586_reg_992 = ap_const_lv1_0) and (or_ln590_3_reg_1054 = ap_const_lv1_1));
    end process;


    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_106, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x_1 <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_x_1 <= x_fu_106;
        end if; 
    end process;


    bytePlanes_plane01_blk_n_assign_proc : process(ap_enable_reg_pp0_iter1, bytePlanes_plane01_full_n, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bytePlanes_plane01_blk_n <= bytePlanes_plane01_full_n;
        else 
            bytePlanes_plane01_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bytePlanes_plane01_din <= (((((((((((((((ap_phi_mux_p_0_3_0_0_0_778_phi_fu_549_p4 & ap_phi_mux_p_0_0_0_0_0_751_phi_fu_569_p4) & ap_phi_reg_pp0_iter1_p_0_3_0_0_0_770_reg_506) & ap_phi_reg_pp0_iter1_p_0_0_0_0_0_743_reg_526) & p_0_3_0_0_0_771_reg_463) & p_0_0_0_0_0_744_reg_485) & p_0_3_0_0_0_772_reg_419) & p_0_0_0_0_0_745_reg_441) & p_0_3_0_0_0_773_reg_375) & p_0_0_0_0_0_746_reg_397) & p_0_3_0_0_0_774_reg_331) & p_0_0_0_0_0_747_reg_353) & p_0_3_0_0_0_775_reg_287) & p_0_0_0_0_0_748_reg_309) & p_0_3_0_0_0_776_reg_246) & p_0_0_0_0_0_749_reg_266);

    bytePlanes_plane01_write_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bytePlanes_plane01_write <= ap_const_logic_1;
        else 
            bytePlanes_plane01_write <= ap_const_logic_0;
        end if; 
    end process;


    bytePlanes_plane12_blk_n_assign_proc : process(ap_enable_reg_pp0_iter1, bytePlanes_plane12_full_n, brmerge42, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (brmerge42 = ap_const_lv1_1))) then 
            bytePlanes_plane12_blk_n <= bytePlanes_plane12_full_n;
        else 
            bytePlanes_plane12_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bytePlanes_plane12_din <= (((((((((((((((ap_phi_mux_p_0_4_0_0_0_787_phi_fu_539_p4 & ap_phi_mux_p_0_1_0_0_0_760_phi_fu_559_p4) & ap_phi_reg_pp0_iter1_p_0_4_0_0_0_779_reg_496) & ap_phi_reg_pp0_iter1_p_0_1_0_0_0_752_reg_516) & p_0_4_0_0_0_780_reg_452) & p_0_1_0_0_0_753_reg_474) & p_0_4_0_0_0_781_reg_408) & p_0_1_0_0_0_754_reg_430) & p_0_4_0_0_0_782_reg_364) & p_0_1_0_0_0_755_reg_386) & p_0_4_0_0_0_783_reg_320) & p_0_1_0_0_0_756_reg_342) & p_0_4_0_0_0_784_reg_276) & p_0_1_0_0_0_757_reg_298) & p_0_4_0_0_0_785_reg_236) & p_0_1_0_0_0_758_reg_256);

    bytePlanes_plane12_write_assign_proc : process(ap_enable_reg_pp0_iter1, brmerge42, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (brmerge42 = ap_const_lv1_1))) then 
            bytePlanes_plane12_write <= ap_const_logic_1;
        else 
            bytePlanes_plane12_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp51_fu_711_p2 <= "1" when (signed(zext_ln586_fu_707_p1) < signed(sub50_cast38_cast_fu_663_p1)) else "0";
    icmp_ln586_fu_695_p2 <= "1" when (ap_sig_allocacmp_x_1 = trunc_ln571_1) else "0";

    img_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, img_empty_n, icmp_ln586_reg_992, ap_predicate_op69_read_state3, ap_CS_fsm_pp0_stage7, ap_predicate_op130_read_state8, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, or_ln590_reg_1007, ap_block_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, or_ln590_2_reg_1045, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4, or_ln590_3_reg_1054, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5, or_ln590_4_reg_1063, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6, or_ln590_5_reg_1067, ap_block_pp0_stage7, ap_block_pp0_stage0, or_ln590_7_reg_1075)
    begin
        if ((((ap_predicate_op130_read_state8 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln590_7_reg_1075 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage6) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (or_ln590_5_reg_1067 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage5) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (or_ln590_4_reg_1063 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage4) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4) and (or_ln590_3_reg_1054 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (or_ln590_2_reg_1045 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_predicate_op69_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (icmp_ln586_reg_992 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln590_reg_1007 = ap_const_lv1_1)))) then 
            img_blk_n <= img_empty_n;
        else 
            img_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_predicate_op69_read_state3, ap_CS_fsm_pp0_stage7, ap_predicate_op130_read_state8, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_predicate_op54_read_state2, ap_block_pp0_stage1_11001, ap_predicate_op93_read_state5, ap_block_pp0_stage4_11001, ap_block_pp0_stage2_11001, ap_predicate_op108_read_state6, ap_block_pp0_stage5_11001, ap_predicate_op141_read_state9, ap_block_pp0_stage0_11001, ap_predicate_op81_read_state4, ap_block_pp0_stage3_11001, ap_predicate_op119_read_state7, ap_block_pp0_stage6_11001, ap_block_pp0_stage7_11001)
    begin
        if ((((ap_predicate_op130_read_state8 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_predicate_op119_read_state7 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_predicate_op81_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op141_read_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_predicate_op108_read_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_predicate_op69_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_predicate_op93_read_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_predicate_op54_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            img_read <= ap_const_logic_1;
        else 
            img_read <= ap_const_logic_0;
        end if; 
    end process;

    or_ln590_1_fu_732_p2 <= (cmp53_1 or cmp51_reg_996);
    or_ln590_2_fu_752_p2 <= (cmp53_2 or cmp51_reg_996);
    or_ln590_3_fu_760_p2 <= (cmp53_3 or cmp51_reg_996);
    or_ln590_4_fu_768_p2 <= (cmp53_4 or cmp51_reg_996);
    or_ln590_5_fu_772_p2 <= (cmp53_5 or cmp51_reg_996);
    or_ln590_6_fu_776_p2 <= (cmp53_6 or cmp51_reg_996);
    or_ln590_7_fu_780_p2 <= (icmp_ln576 or cmp51_reg_996);
    or_ln590_fu_717_p2 <= (cmp53 or cmp51_fu_711_p2);
    p_0_0_0_0_0_750_out <= p_0_0_0_0_0_750_fu_110;

    p_0_0_0_0_0_750_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln586_reg_992, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln586_reg_992 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            p_0_0_0_0_0_750_out_ap_vld <= ap_const_logic_1;
        else 
            p_0_0_0_0_0_750_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_0_1_0_0_0_759_out <= p_0_1_0_0_0_759_fu_114;

    p_0_1_0_0_0_759_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln586_reg_992, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln586_reg_992 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            p_0_1_0_0_0_759_out_ap_vld <= ap_const_logic_1;
        else 
            p_0_1_0_0_0_759_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_0_3_0_0_0_777_out <= p_0_3_0_0_0_777_fu_118;

    p_0_3_0_0_0_777_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln586_reg_992, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln586_reg_992 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            p_0_3_0_0_0_777_out_ap_vld <= ap_const_logic_1;
        else 
            p_0_3_0_0_0_777_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_0_4_0_0_0_786_out <= p_0_4_0_0_0_786_fu_122;

    p_0_4_0_0_0_786_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln586_reg_992, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln586_reg_992 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            p_0_4_0_0_0_786_out_ap_vld <= ap_const_logic_1;
        else 
            p_0_4_0_0_0_786_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        sub50_cast38_cast_fu_663_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub50_cast38),13));

    trunc_ln145_11_fu_784_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln145_14_fu_788_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln145_17_fu_792_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln145_20_fu_796_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln145_4_fu_748_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln145_5_fu_756_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln145_8_fu_764_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln145_fu_728_p1 <= img_dout(8 - 1 downto 0);
    x_2_fu_701_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_1) + unsigned(ap_const_lv12_1));
    zext_ln586_fu_707_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_x_1),13));
end behav;
