-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_MultiPixStream2Bytes is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    img_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_empty_n : IN STD_LOGIC;
    img_read : OUT STD_LOGIC;
    bytePlanes_plane01_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    bytePlanes_plane01_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
    bytePlanes_plane01_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
    bytePlanes_plane01_full_n : IN STD_LOGIC;
    bytePlanes_plane01_write : OUT STD_LOGIC;
    bytePlanes_plane12_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    bytePlanes_plane12_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
    bytePlanes_plane12_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
    bytePlanes_plane12_full_n : IN STD_LOGIC;
    bytePlanes_plane12_write : OUT STD_LOGIC;
    Height_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    Height_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    Height_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    Height_empty_n : IN STD_LOGIC;
    Height_read : OUT STD_LOGIC;
    WidthInBytes_dout : IN STD_LOGIC_VECTOR (14 downto 0);
    WidthInBytes_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_empty_n : IN STD_LOGIC;
    WidthInBytes_read : OUT STD_LOGIC;
    VideoFormat_dout : IN STD_LOGIC_VECTOR (5 downto 0);
    VideoFormat_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    VideoFormat_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    VideoFormat_empty_n : IN STD_LOGIC;
    VideoFormat_read : OUT STD_LOGIC;
    WidthInBytes_c_din : OUT STD_LOGIC_VECTOR (14 downto 0);
    WidthInBytes_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    WidthInBytes_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    WidthInBytes_c_full_n : IN STD_LOGIC;
    WidthInBytes_c_write : OUT STD_LOGIC;
    height_c_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    height_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    height_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    height_c_full_n : IN STD_LOGIC;
    height_c_write : OUT STD_LOGIC;
    video_format_c_din : OUT STD_LOGIC_VECTOR (5 downto 0);
    video_format_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    video_format_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    video_format_c_full_n : IN STD_LOGIC;
    video_format_c_write : OUT STD_LOGIC );
end;


architecture behav of kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_MultiPixStream2Bytes is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv16_F : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal Height_blk_n : STD_LOGIC;
    signal WidthInBytes_blk_n : STD_LOGIC;
    signal VideoFormat_blk_n : STD_LOGIC;
    signal WidthInBytes_c_blk_n : STD_LOGIC;
    signal height_c_blk_n : STD_LOGIC;
    signal video_format_c_blk_n : STD_LOGIC;
    signal VideoFormat_read_read_fu_158_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal VideoFormat_read_reg_403 : STD_LOGIC_VECTOR (5 downto 0);
    signal Height_read_reg_407 : STD_LOGIC_VECTOR (11 downto 0);
    signal widthInPix_reg_412 : STD_LOGIC_VECTOR (14 downto 0);
    signal notlhs_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal notlhs_reg_450 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln571_1_fu_252_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln571_1_reg_455 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln576_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln576_reg_460 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub50_fu_289_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub50_reg_465 : STD_LOGIC_VECTOR (11 downto 0);
    signal cmp53_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp53_reg_470 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_475 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp53_2_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp53_2_reg_480 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp6_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp6_reg_485 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp53_4_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp53_4_reg_490 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp53_5_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp53_5_reg_495 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp53_6_fu_351_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp53_6_reg_500 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_0_0_0_0_751_lcssa99_load_reg_508 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln583_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_1_0_0_0_760_lcssa102_load_reg_513 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_3_0_0_0_778_lcssa108_load_reg_518 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_4_0_0_0_787_lcssa111_load_reg_523 : STD_LOGIC_VECTOR (7 downto 0);
    signal brmerge42_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge42_reg_528 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_img_read : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_write : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_write : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal p_0_4_0_0_0_787_lcssa111_fu_154 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_3_0_0_0_778_lcssa108_fu_150 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0_760_lcssa102_fu_146 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0_751_lcssa99_fu_142 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_fu_138 : STD_LOGIC_VECTOR (11 downto 0);
    signal y_2_fu_369_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal zext_ln571_fu_243_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln571_fu_246_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal remainPix_fu_240_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal lshr_ln_fu_268_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln578_fu_277_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal remainPix_1_fu_281_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_301_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_323_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln583_fu_360_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool_not_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_empty_n : IN STD_LOGIC;
        img_read : OUT STD_LOGIC;
        p_0_4_0_0_0_787_lcssa111 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_3_0_0_0_778_lcssa108 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0_760_lcssa102 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0_751_lcssa99 : IN STD_LOGIC_VECTOR (7 downto 0);
        trunc_ln571_1 : IN STD_LOGIC_VECTOR (11 downto 0);
        bytePlanes_plane12_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        bytePlanes_plane12_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
        bytePlanes_plane12_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
        bytePlanes_plane12_full_n : IN STD_LOGIC;
        bytePlanes_plane12_write : OUT STD_LOGIC;
        bytePlanes_plane01_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        bytePlanes_plane01_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
        bytePlanes_plane01_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
        bytePlanes_plane01_full_n : IN STD_LOGIC;
        bytePlanes_plane01_write : OUT STD_LOGIC;
        brmerge42 : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp_ln576 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp53_6 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp53_5 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp53_4 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp53_3 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp53_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp53_1 : IN STD_LOGIC_VECTOR (0 downto 0);
        sub50_cast38 : IN STD_LOGIC_VECTOR (11 downto 0);
        cmp53 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_0_4_0_0_0_786_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_4_0_0_0_786_out_ap_vld : OUT STD_LOGIC;
        p_0_3_0_0_0_777_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_3_0_0_0_777_out_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_0_759_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0_759_out_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0_750_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0_750_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200 : component kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start,
        ap_done => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_done,
        ap_idle => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_idle,
        ap_ready => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_ready,
        img_dout => img_dout,
        img_num_data_valid => ap_const_lv2_0,
        img_fifo_cap => ap_const_lv2_0,
        img_empty_n => img_empty_n,
        img_read => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_img_read,
        p_0_4_0_0_0_787_lcssa111 => p_0_4_0_0_0_787_lcssa111_load_reg_523,
        p_0_3_0_0_0_778_lcssa108 => p_0_3_0_0_0_778_lcssa108_load_reg_518,
        p_0_1_0_0_0_760_lcssa102 => p_0_1_0_0_0_760_lcssa102_load_reg_513,
        p_0_0_0_0_0_751_lcssa99 => p_0_0_0_0_0_751_lcssa99_load_reg_508,
        trunc_ln571_1 => trunc_ln571_1_reg_455,
        bytePlanes_plane12_din => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_din,
        bytePlanes_plane12_num_data_valid => ap_const_lv10_0,
        bytePlanes_plane12_fifo_cap => ap_const_lv10_0,
        bytePlanes_plane12_full_n => bytePlanes_plane12_full_n,
        bytePlanes_plane12_write => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_write,
        bytePlanes_plane01_din => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_din,
        bytePlanes_plane01_num_data_valid => ap_const_lv10_0,
        bytePlanes_plane01_fifo_cap => ap_const_lv10_0,
        bytePlanes_plane01_full_n => bytePlanes_plane01_full_n,
        bytePlanes_plane01_write => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_write,
        brmerge42 => brmerge42_reg_528,
        icmp_ln576 => icmp_ln576_reg_460,
        cmp53_6 => cmp53_6_reg_500,
        cmp53_5 => cmp53_5_reg_495,
        cmp53_4 => cmp53_4_reg_490,
        cmp53_3 => icmp6_reg_485,
        cmp53_2 => cmp53_2_reg_480,
        cmp53_1 => icmp_reg_475,
        sub50_cast38 => sub50_reg_465,
        cmp53 => cmp53_reg_470,
        p_0_4_0_0_0_786_out => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out,
        p_0_4_0_0_0_786_out_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out_ap_vld,
        p_0_3_0_0_0_777_out => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out,
        p_0_3_0_0_0_777_out_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out_ap_vld,
        p_0_1_0_0_0_759_out => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out,
        p_0_1_0_0_0_759_out_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out_ap_vld,
        p_0_0_0_0_0_750_out => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out,
        p_0_0_0_0_0_750_out_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and ((icmp_ln583_fu_364_p2 = ap_const_lv1_1) or (not((ap_const_lv6_12 = VideoFormat_read_reg_403)) and not((ap_const_lv6_13 = VideoFormat_read_reg_403)))))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((ap_const_lv6_13 = VideoFormat_read_read_fu_158_p2) or (ap_const_lv6_12 = VideoFormat_read_read_fu_158_p2)))) then 
                y_fu_138 <= ap_const_lv12_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (((icmp_ln583_fu_364_p2 = ap_const_lv1_0) and (ap_const_lv6_12 = VideoFormat_read_reg_403)) or ((ap_const_lv6_13 = VideoFormat_read_reg_403) and (icmp_ln583_fu_364_p2 = ap_const_lv1_0))))) then 
                y_fu_138 <= y_2_fu_369_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                Height_read_reg_407 <= Height_dout;
                VideoFormat_read_reg_403 <= VideoFormat_dout;
                widthInPix_reg_412 <= WidthInBytes_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (((icmp_ln583_fu_364_p2 = ap_const_lv1_0) and (ap_const_lv6_12 = VideoFormat_read_reg_403)) or ((ap_const_lv6_13 = VideoFormat_read_reg_403) and (icmp_ln583_fu_364_p2 = ap_const_lv1_0))))) then
                brmerge42_reg_528 <= brmerge42_fu_393_p2;
                p_0_0_0_0_0_751_lcssa99_load_reg_508 <= p_0_0_0_0_0_751_lcssa99_fu_142;
                p_0_1_0_0_0_760_lcssa102_load_reg_513 <= p_0_1_0_0_0_760_lcssa102_fu_146;
                p_0_3_0_0_0_778_lcssa108_load_reg_518 <= p_0_3_0_0_0_778_lcssa108_fu_150;
                p_0_4_0_0_0_787_lcssa111_load_reg_523 <= p_0_4_0_0_0_787_lcssa111_fu_154;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                cmp53_2_reg_480 <= cmp53_2_fu_317_p2;
                cmp53_4_reg_490 <= cmp53_4_fu_339_p2;
                cmp53_5_reg_495 <= cmp53_5_fu_345_p2;
                cmp53_6_reg_500 <= cmp53_6_fu_351_p2;
                cmp53_reg_470 <= cmp53_fu_295_p2;
                icmp6_reg_485 <= icmp6_fu_333_p2;
                icmp_ln576_reg_460 <= icmp_ln576_fu_262_p2;
                icmp_reg_475 <= icmp_fu_311_p2;
                sub50_reg_465 <= sub50_fu_289_p2;
                trunc_ln571_1_reg_455 <= add_ln571_fu_246_p2(15 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and ((ap_const_lv6_13 = VideoFormat_read_read_fu_158_p2) or (ap_const_lv6_12 = VideoFormat_read_read_fu_158_p2)))) then
                notlhs_reg_450 <= notlhs_fu_229_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out_ap_vld = ap_const_logic_1))) then
                p_0_0_0_0_0_751_lcssa99_fu_142 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_0_0_0_0_750_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out_ap_vld = ap_const_logic_1))) then
                p_0_1_0_0_0_760_lcssa102_fu_146 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_1_0_0_0_759_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out_ap_vld = ap_const_logic_1))) then
                p_0_3_0_0_0_778_lcssa108_fu_150 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_3_0_0_0_777_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out_ap_vld = ap_const_logic_1))) then
                p_0_4_0_0_0_787_lcssa111_fu_154 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_p_0_4_0_0_0_786_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n, VideoFormat_read_read_fu_158_p2, VideoFormat_read_reg_403, ap_CS_fsm_state3, icmp_ln583_fu_364_p2, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_done, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and not((ap_const_lv6_12 = VideoFormat_read_read_fu_158_p2)) and not((ap_const_lv6_13 = VideoFormat_read_read_fu_158_p2)) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((ap_const_lv6_13 = VideoFormat_read_read_fu_158_p2) or (ap_const_lv6_12 = VideoFormat_read_read_fu_158_p2)))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((icmp_ln583_fu_364_p2 = ap_const_lv1_1) or (not((ap_const_lv6_12 = VideoFormat_read_reg_403)) and not((ap_const_lv6_13 = VideoFormat_read_reg_403)))))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;

    Height_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Height_blk_n <= Height_empty_n;
        else 
            Height_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Height_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Height_read <= ap_const_logic_1;
        else 
            Height_read <= ap_const_logic_0;
        end if; 
    end process;


    VideoFormat_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, VideoFormat_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            VideoFormat_blk_n <= VideoFormat_empty_n;
        else 
            VideoFormat_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    VideoFormat_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            VideoFormat_read <= ap_const_logic_1;
        else 
            VideoFormat_read <= ap_const_logic_0;
        end if; 
    end process;

    VideoFormat_read_read_fu_158_p2 <= VideoFormat_dout;

    WidthInBytes_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, WidthInBytes_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_blk_n <= WidthInBytes_empty_n;
        else 
            WidthInBytes_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    WidthInBytes_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, WidthInBytes_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_c_blk_n <= WidthInBytes_c_full_n;
        else 
            WidthInBytes_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    WidthInBytes_c_din <= WidthInBytes_dout;

    WidthInBytes_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_c_write <= ap_const_logic_1;
        else 
            WidthInBytes_c_write <= ap_const_logic_0;
        end if; 
    end process;


    WidthInBytes_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_read <= ap_const_logic_1;
        else 
            WidthInBytes_read <= ap_const_logic_0;
        end if; 
    end process;

    add_ln571_fu_246_p2 <= std_logic_vector(unsigned(zext_ln571_fu_243_p1) + unsigned(ap_const_lv16_F));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if (((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_done)
    begin
        if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
                ap_block_state1 <= ((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, VideoFormat_read_reg_403, ap_CS_fsm_state3, icmp_ln583_fu_364_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((icmp_ln583_fu_364_p2 = ap_const_lv1_1) or (not((ap_const_lv6_12 = VideoFormat_read_reg_403)) and not((ap_const_lv6_13 = VideoFormat_read_reg_403)))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(VideoFormat_read_reg_403, ap_CS_fsm_state3, icmp_ln583_fu_364_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((icmp_ln583_fu_364_p2 = ap_const_lv1_1) or (not((ap_const_lv6_12 = VideoFormat_read_reg_403)) and not((ap_const_lv6_13 = VideoFormat_read_reg_403)))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    brmerge42_fu_393_p2 <= (tobool_not_fu_387_p2 or notlhs_reg_450);
    bytePlanes_plane01_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_din;

    bytePlanes_plane01_write_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_write, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            bytePlanes_plane01_write <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane01_write;
        else 
            bytePlanes_plane01_write <= ap_const_logic_0;
        end if; 
    end process;

    bytePlanes_plane12_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_din;

    bytePlanes_plane12_write_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_write, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            bytePlanes_plane12_write <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_bytePlanes_plane12_write;
        else 
            bytePlanes_plane12_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp53_2_fu_317_p2 <= "1" when (unsigned(remainPix_1_fu_281_p3) > unsigned(ap_const_lv4_2)) else "0";
    cmp53_4_fu_339_p2 <= "1" when (unsigned(remainPix_1_fu_281_p3) > unsigned(ap_const_lv4_4)) else "0";
    cmp53_5_fu_345_p2 <= "1" when (unsigned(remainPix_1_fu_281_p3) > unsigned(ap_const_lv4_5)) else "0";
    cmp53_6_fu_351_p2 <= "1" when (unsigned(remainPix_1_fu_281_p3) > unsigned(ap_const_lv4_6)) else "0";
    cmp53_fu_295_p2 <= "0" when (remainPix_1_fu_281_p3 = ap_const_lv4_0) else "1";
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_ap_start_reg;

    height_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_c_blk_n <= height_c_full_n;
        else 
            height_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_c_din <= Height_dout;

    height_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_c_write <= ap_const_logic_1;
        else 
            height_c_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp6_fu_333_p2 <= "0" when (tmp_1_fu_323_p4 = ap_const_lv2_0) else "1";
    icmp_fu_311_p2 <= "0" when (tmp_fu_301_p4 = ap_const_lv3_0) else "1";
    icmp_ln576_fu_262_p2 <= "1" when (remainPix_fu_240_p1 = ap_const_lv4_0) else "0";
    icmp_ln583_fu_364_p2 <= "1" when (y_fu_138 = Height_read_reg_407) else "0";

    img_read_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_img_read, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            img_read <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_1_fu_200_img_read;
        else 
            img_read <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln_fu_268_p4 <= widthInPix_reg_412(3 downto 1);
    notlhs_fu_229_p2 <= "0" when (VideoFormat_dout = ap_const_lv6_13) else "1";
    remainPix_1_fu_281_p3 <= 
        ap_const_lv4_8 when (icmp_ln576_fu_262_p2(0) = '1') else 
        zext_ln578_fu_277_p1;
    remainPix_fu_240_p1 <= widthInPix_reg_412(4 - 1 downto 0);
    sub50_fu_289_p2 <= std_logic_vector(unsigned(trunc_ln571_1_fu_252_p4) + unsigned(ap_const_lv12_FFF));
    tmp_1_fu_323_p4 <= remainPix_1_fu_281_p3(3 downto 2);
    tmp_fu_301_p4 <= remainPix_1_fu_281_p3(3 downto 1);
    tobool_not_fu_387_p2 <= (trunc_ln583_fu_360_p1 xor ap_const_lv1_1);
    trunc_ln571_1_fu_252_p4 <= add_ln571_fu_246_p2(15 downto 4);
    trunc_ln583_fu_360_p1 <= y_fu_138(1 - 1 downto 0);

    video_format_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, video_format_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            video_format_c_blk_n <= video_format_c_full_n;
        else 
            video_format_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    video_format_c_din <= VideoFormat_dout;

    video_format_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            video_format_c_write <= ap_const_logic_1;
        else 
            video_format_c_write <= ap_const_logic_0;
        end if; 
    end process;

    y_2_fu_369_p2 <= std_logic_vector(unsigned(y_fu_138) + unsigned(ap_const_lv12_1));
    zext_ln571_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(widthInPix_reg_412),16));
    zext_ln578_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_268_p4),4));
end behav;
