// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        img_din,
        img_num_data_valid,
        img_fifo_cap,
        img_full_n,
        img_write,
        p_read,
        p_read1,
        p_read2,
        height_c10_din,
        height_c10_num_data_valid,
        height_c10_fifo_cap,
        height_c10_full_n,
        height_c10_write
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [47:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [5:0] s_axis_video_TKEEP;
input  [5:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [47:0] img_din;
input  [1:0] img_num_data_valid;
input  [1:0] img_fifo_cap;
input   img_full_n;
output   img_write;
input  [11:0] p_read;
input  [11:0] p_read1;
input  [2:0] p_read2;
output  [11:0] height_c10_din;
input  [1:0] height_c10_num_data_valid;
input  [1:0] height_c10_fifo_cap;
input   height_c10_full_n;
output   height_c10_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg s_axis_video_TREADY;
reg img_write;
reg height_c10_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    height_c10_blk_n;
reg   [10:0] div_cast_reg_413;
wire    ap_CS_fsm_state2;
wire   [11:0] grp_reg_unsigned_short_s_fu_293_ap_return;
reg   [11:0] rows_reg_419;
wire    ap_CS_fsm_state4;
wire   [0:0] cmp8460_fu_301_p2;
reg   [0:0] cmp8460_reg_427;
wire   [0:0] cond_fu_306_p2;
reg   [0:0] cond_reg_431;
wire   [0:0] icmp_ln235_fu_311_p2;
reg   [0:0] icmp_ln235_reg_436;
wire   [11:0] i_2_fu_328_p2;
reg   [11:0] i_2_reg_447;
wire    ap_CS_fsm_state5;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_ready;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_s_axis_video_TREADY;
wire   [47:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_axi_data_V_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_axi_data_V_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_axi_last_V_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_axi_last_V_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_ready;
wire   [47:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_img_din;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_img_write;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_s_axis_video_TREADY;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_eol_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_eol_out_ap_vld;
wire   [47:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_axi_data_V_3_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_axi_data_V_3_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_ready;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_s_axis_video_TREADY;
wire   [47:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_data_V_4_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_data_V_4_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_last_V_4_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_last_V_4_out_ap_vld;
wire   [11:0] grp_reg_unsigned_short_s_fu_267_ap_return;
reg   [0:0] axi_last_V_2_reg_148;
wire    ap_CS_fsm_state10;
reg   [47:0] axi_data_2_lcssa_reg_158;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln205_fu_323_p2;
reg   [0:0] axi_last_2_lcssa_reg_168;
reg   [0:0] eol_0_lcssa_reg_179;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [47:0] axi_data_V_2_fu_98;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [0:0] axi_last_V_4_loc_fu_106;
reg   [11:0] i_fu_94;
reg    ap_block_state1;
reg   [0:0] sof_fu_102;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 10'd1;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_start_reg = 1'b0;
end

kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .axi_data_V_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_axi_data_V_out),
    .axi_data_V_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_axi_data_V_out_ap_vld),
    .axi_last_V_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_axi_last_V_out),
    .axi_last_V_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_axi_last_V_out_ap_vld)
);

kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_width grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .img_din(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_img_din),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_full_n(img_full_n),
    .img_write(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_img_write),
    .sof_2(sof_fu_102),
    .axi_last_V_2(axi_last_V_2_reg_148),
    .axi_data_V_2(axi_data_V_2_fu_98),
    .div_cast(div_cast_reg_413),
    .cond(cond_reg_431),
    .p_read2(p_read2),
    .icmp_ln235(icmp_ln235_reg_436),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .eol_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_eol_out),
    .eol_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_eol_out_ap_vld),
    .axi_data_V_3_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_axi_data_V_3_out),
    .axi_data_V_3_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_axi_data_V_3_out_ap_vld)
);

kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .axi_data_2_lcssa(axi_data_2_lcssa_reg_158),
    .axi_last_2_lcssa(axi_last_2_lcssa_reg_168),
    .eol_0_lcssa(eol_0_lcssa_reg_179),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .axi_data_V_4_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_data_V_4_out),
    .axi_data_V_4_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_data_V_4_out_ap_vld),
    .axi_last_V_4_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_last_V_4_out),
    .axi_last_V_4_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_last_V_4_out_ap_vld)
);

kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_267(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(p_read1),
    .ap_return(grp_reg_unsigned_short_s_fu_267_ap_return)
);

kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_293(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(p_read),
    .ap_return(grp_reg_unsigned_short_s_fu_293_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln205_fu_323_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_start_reg <= 1'b0;
    end else begin
        if (((cmp8460_reg_427 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln205_fu_323_p2 == 1'd0))) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((cmp8460_reg_427 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln205_fu_323_p2 == 1'd0))) begin
        axi_data_2_lcssa_reg_158 <= axi_data_V_2_fu_98;
    end else if (((cmp8460_reg_427 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        axi_data_2_lcssa_reg_158 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_axi_data_V_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_data_V_4_out_ap_vld == 1'b1))) begin
        axi_data_V_2_fu_98 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_data_V_4_out;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_axi_data_V_out_ap_vld == 1'b1))) begin
        axi_data_V_2_fu_98 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_axi_data_V_out;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp8460_reg_427 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln205_fu_323_p2 == 1'd0))) begin
        axi_last_2_lcssa_reg_168 <= axi_last_V_2_reg_148;
    end else if (((cmp8460_reg_427 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        axi_last_2_lcssa_reg_168 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_eol_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_last_V_2_reg_148 <= axi_last_V_4_loc_fu_106;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_V_2_reg_148 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_axi_last_V_out;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp8460_reg_427 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln205_fu_323_p2 == 1'd0))) begin
        eol_0_lcssa_reg_179 <= 1'd0;
    end else if (((cmp8460_reg_427 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        eol_0_lcssa_reg_179 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_eol_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((height_c10_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_94 <= 12'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i_fu_94 <= i_2_reg_447;
    end
end

always @ (posedge ap_clk) begin
    if ((~((height_c10_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        sof_fu_102 <= 1'd1;
    end else if (((cmp8460_reg_427 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        sof_fu_102 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_last_V_4_out_ap_vld == 1'b1))) begin
        axi_last_V_4_loc_fu_106 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_axi_last_V_4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cmp8460_reg_427 <= cmp8460_fu_301_p2;
        cond_reg_431 <= cond_fu_306_p2;
        icmp_ln235_reg_436 <= icmp_ln235_fu_311_p2;
        rows_reg_419 <= grp_reg_unsigned_short_s_fu_293_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        div_cast_reg_413 <= {{grp_reg_unsigned_short_s_fu_267_ap_return[11:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_2_reg_447 <= i_2_fu_328_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if (((height_c10_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln205_fu_323_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln205_fu_323_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c10_blk_n = height_c10_full_n;
    end else begin
        height_c10_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c10_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c10_write = 1'b1;
    end else begin
        height_c10_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        img_write = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_img_write;
    end else begin
        img_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        s_axis_video_TREADY = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        s_axis_video_TREADY = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_video_TREADY = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((height_c10_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln205_fu_323_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((cmp8460_reg_427 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln205_fu_323_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((height_c10_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign cmp8460_fu_301_p2 = ((div_cast_reg_413 == 11'd0) ? 1'b1 : 1'b0);

assign cond_fu_306_p2 = ((p_read2 == 3'd0) ? 1'b1 : 1'b0);

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_241_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_191_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_ap_start_reg;

assign height_c10_din = p_read;

assign i_2_fu_328_p2 = (i_fu_94 + 12'd1);

assign icmp_ln205_fu_323_p2 = ((i_fu_94 == rows_reg_419) ? 1'b1 : 1'b0);

assign icmp_ln235_fu_311_p2 = ((p_read2 == 3'd1) ? 1'b1 : 1'b0);

assign img_din = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_211_img_din;

endmodule //kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0_AXIvideo2MultiPixStream
