# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/pin.xdc

# Block Designs: bd/kv260_ispMipiRx_vcu_DP/kv260_ispMipiRx_vcu_DP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_PS_0_0/kv260_ispMipiRx_vcu_DP_PS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_PS_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_PS_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_audio_formatter_0_0/kv260_ispMipiRx_vcu_DP_audio_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_audio_formatter_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_audio_formatter_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axi_clock_converter_mm2s_0/kv260_ispMipiRx_vcu_DP_axi_clock_converter_mm2s_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axi_clock_converter_mm2s_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axi_clock_converter_mm2s_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axi_clock_converter_s2mm_0/kv260_ispMipiRx_vcu_DP_axi_clock_converter_s2mm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axi_clock_converter_s2mm_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axi_clock_converter_s2mm_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_clk_wiz_audio_0/kv260_ispMipiRx_vcu_DP_clk_wiz_audio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_clk_wiz_audio_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_clk_wiz_audio_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_i2s_receiver_0_0/kv260_ispMipiRx_vcu_DP_i2s_receiver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_i2s_receiver_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_i2s_receiver_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_i2s_transmitter_0_0/kv260_ispMipiRx_vcu_DP_i2s_transmitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_i2s_transmitter_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_i2s_transmitter_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_oddr_rx_0/kv260_ispMipiRx_vcu_DP_oddr_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_oddr_rx_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_oddr_rx_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_oddr_tx_0/kv260_ispMipiRx_vcu_DP_oddr_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_oddr_tx_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_oddr_tx_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_proc_sys_reset_18MHz_0/kv260_ispMipiRx_vcu_DP_proc_sys_reset_18MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_proc_sys_reset_18MHz_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_proc_sys_reset_18MHz_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s00_regslice_5/kv260_ispMipiRx_vcu_DP_s00_regslice_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s00_regslice_5 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s00_regslice_5} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axi_ic_accel_ctrl_0/kv260_ispMipiRx_vcu_DP_axi_ic_accel_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_accel_ctrl_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_accel_ctrl_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_xbar_0/kv260_ispMipiRx_vcu_DP_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_xbar_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_xbar_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s00_regslice_6/kv260_ispMipiRx_vcu_DP_s00_regslice_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s00_regslice_6 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s00_regslice_6} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_auto_us_0/kv260_ispMipiRx_vcu_DP_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_auto_us_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_auto_us_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s01_regslice_3/kv260_ispMipiRx_vcu_DP_s01_regslice_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s01_regslice_3 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s01_regslice_3} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_auto_us_1/kv260_ispMipiRx_vcu_DP_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_auto_us_1 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_auto_us_1} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s02_regslice_0/kv260_ispMipiRx_vcu_DP_s02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s02_regslice_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s02_regslice_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_auto_us_2/kv260_ispMipiRx_vcu_DP_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_auto_us_2 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_auto_us_2} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_m00_regslice_3/kv260_ispMipiRx_vcu_DP_m00_regslice_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_m00_regslice_3 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_m00_regslice_3} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s00_mmu_0/kv260_ispMipiRx_vcu_DP_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s00_mmu_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s00_mmu_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s01_mmu_0/kv260_ispMipiRx_vcu_DP_s01_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s01_mmu_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s01_mmu_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s02_mmu_0/kv260_ispMipiRx_vcu_DP_s02_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s02_mmu_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s02_mmu_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axi_ic_audio_mcu_0/kv260_ispMipiRx_vcu_DP_axi_ic_audio_mcu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_audio_mcu_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_audio_mcu_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_xbar_1/kv260_ispMipiRx_vcu_DP_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_xbar_1 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_xbar_1} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s00_regslice_7/kv260_ispMipiRx_vcu_DP_s00_regslice_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s00_regslice_7 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s00_regslice_7} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_auto_pc_0/kv260_ispMipiRx_vcu_DP_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_auto_pc_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_auto_pc_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axi_ic_ctrl_100_0/kv260_ispMipiRx_vcu_DP_axi_ic_ctrl_100_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_ctrl_100_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_ctrl_100_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_auto_pc_1/kv260_ispMipiRx_vcu_DP_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_auto_pc_1 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_auto_pc_1} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axi_ic_ctrl_300_0/kv260_ispMipiRx_vcu_DP_axi_ic_ctrl_300_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_ctrl_300_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_ctrl_300_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axi_iic_0_0/kv260_ispMipiRx_vcu_DP_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axi_iic_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axi_iic_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axi_vip_0_0/kv260_ispMipiRx_vcu_DP_axi_vip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axi_vip_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axi_vip_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axis_data_fifo_cap_0/kv260_ispMipiRx_vcu_DP_axis_data_fifo_cap_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axis_data_fifo_cap_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axis_data_fifo_cap_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axis_subset_converter_0_0/kv260_ispMipiRx_vcu_DP_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axis_subset_converter_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_0/kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_mipi_csi2_rx_subsyst_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0/kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_v_frmbuf_wr_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_xlslice_0_0/kv260_ispMipiRx_vcu_DP_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_xlslice_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_xlslice_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_clk_wiz_0_0/kv260_ispMipiRx_vcu_DP_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_clk_wiz_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_clk_wiz_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_proc_sys_reset_100MHz_0/kv260_ispMipiRx_vcu_DP_proc_sys_reset_100MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_proc_sys_reset_100MHz_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_proc_sys_reset_100MHz_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_proc_sys_reset_300MHz_0/kv260_ispMipiRx_vcu_DP_proc_sys_reset_300MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_proc_sys_reset_300MHz_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_proc_sys_reset_300MHz_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_proc_sys_reset_600MHz_0/kv260_ispMipiRx_vcu_DP_proc_sys_reset_600MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_proc_sys_reset_600MHz_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_proc_sys_reset_600MHz_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_xbar_2/kv260_ispMipiRx_vcu_DP_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_xbar_2 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_xbar_2} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s00_regslice_8/kv260_ispMipiRx_vcu_DP_s00_regslice_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s00_regslice_8 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s00_regslice_8} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s01_regslice_4/kv260_ispMipiRx_vcu_DP_s01_regslice_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s01_regslice_4 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s01_regslice_4} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_m00_regslice_4/kv260_ispMipiRx_vcu_DP_m00_regslice_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_m00_regslice_4 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_m00_regslice_4} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s00_mmu_1/kv260_ispMipiRx_vcu_DP_s00_mmu_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s00_mmu_1 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s00_mmu_1} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s01_mmu_1/kv260_ispMipiRx_vcu_DP_s01_mmu_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s01_mmu_1 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s01_mmu_1} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axi_ic_vcu_dec_0/kv260_ispMipiRx_vcu_DP_axi_ic_vcu_dec_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_vcu_dec_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_vcu_dec_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_xbar_3/kv260_ispMipiRx_vcu_DP_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_xbar_3 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_xbar_3} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s00_regslice_9/kv260_ispMipiRx_vcu_DP_s00_regslice_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s00_regslice_9 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s00_regslice_9} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s01_regslice_5/kv260_ispMipiRx_vcu_DP_s01_regslice_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s01_regslice_5 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s01_regslice_5} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_m00_regslice_5/kv260_ispMipiRx_vcu_DP_m00_regslice_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_m00_regslice_5 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_m00_regslice_5} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s00_mmu_2/kv260_ispMipiRx_vcu_DP_s00_mmu_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s00_mmu_2 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s00_mmu_2} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_s01_mmu_2/kv260_ispMipiRx_vcu_DP_s01_mmu_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_s01_mmu_2 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_s01_mmu_2} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axi_ic_vcu_enc_0/kv260_ispMipiRx_vcu_DP_axi_ic_vcu_enc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_vcu_enc_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axi_ic_vcu_enc_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_axi_reg_slice_vmcu_0/kv260_ispMipiRx_vcu_DP_axi_reg_slice_vmcu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_axi_reg_slice_vmcu_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_axi_reg_slice_vmcu_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_vcu_0_0/kv260_ispMipiRx_vcu_DP_vcu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_vcu_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_vcu_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_xlslice_0_1/kv260_ispMipiRx_vcu_DP_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_xlslice_0_1 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_xlslice_0_1} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_xlconcat_0_0_0/kv260_ispMipiRx_vcu_DP_xlconcat_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_xlconcat_0_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_xlconcat_0_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_xlconstant_0_0/kv260_ispMipiRx_vcu_DP_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_xlconstant_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_xlconstant_0_0} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_xlslice_0_2/kv260_ispMipiRx_vcu_DP_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_xlslice_0_2 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_xlslice_0_2} -quiet] -quiet

# IP: bd/kv260_ispMipiRx_vcu_DP/ip/kv260_ispMipiRx_vcu_DP_xlslice_ttc_0_0/kv260_ispMipiRx_vcu_DP_xlslice_ttc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kv260_ispMipiRx_vcu_DP_xlslice_ttc_0_0 || ORIG_REF_NAME==kv260_ispMipiRx_vcu_DP_xlslice_ttc_0_0} -quiet] -quiet

# XDC: /home/anubhav/Documents/kria-vitis-platforms/kv260/platforms/vivado/kv260_ispMipiRx_vcu_DP/project/kv260_ispMipiRx_vcu_DP.gen/sources_1/bd/kv260_ispMipiRx_vcu_DP/kv260_ispMipiRx_vcu_DP_ooc.xdc
